function Cbarxx = D2CbarDxx(in1)
%D2CbarDxx
%    Cbarxx = D2CbarDxx(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:27

Cbarxx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,2,4]);
end
