function Cxu = D2CDxu(in1,in2)
%D2CDxu
%    Cxu = D2CDxu(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:26

Cxu = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,2,4]);
end
