function Cuu = D2CDuu(in1,in2)
%D2CDuu
%    Cuu = D2CDuu(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:26

Cuu = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,2,4]);
end
