function fxu = D2fDxu(in1,in2)
%D2fDxu
%    FXU = D2fDxu(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:25

fxu = reshape([-2.698808054141969e-2,-3.727623637827758e-2,1.558099266866979e-2,2.101243516732921e-2,-8.824094613274776e-4,1.989542483373983e-2,-1.129513758621841e-2,-1.264345508372994e-2],[2,2,2]);
end
