function fxx = D2fDxx(in1,in2)
%D2fDxx
%    FXX = D2fDxx(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:25

fxx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,2,2]);
end
