function fuu = D2fDuu(in1,in2)
%D2fDuu
%    FUU = D2fDuu(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:25

fuu = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,2,2]);
end
