function Luu = D2LDuu(in1,in2,in3)
%D2LDuu
%    Luu = D2LDuu(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:25

Luu = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
