function Cbarx = DCbarDx(in1)
%DCbarDx
%    Cbarx = DCbarDx(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:26

Cbarx = reshape([1.0,0.0,-1.0,0.0,0.0,1.0,0.0,-1.0],[4,2]);
end
