function Cu = DCDu(in1,in2)
%DCDu
%    Cu = DCDu(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:26

Cu = reshape([9.583633947975842e+2,0.0,-9.583633947975842e+2,0.0,0.0,1.099625344204039e+3,0.0,-1.099625344204039e+3],[4,2]);
end
