function Cx = DCDx(in1,in2)
%DCDx
%    Cx = DCDx(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:25

Cx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,2]);
end
