function Lx = DLDx(in1,in2,in3)
%DLDx
%    Lx = DLDx(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:25

r1 = in3(:,1);
r2 = in3(:,2);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = conj(x1);
t3 = conj(x2);
et1 = r1.*1.023436137921772e+1-r2.*3.246987961585796;
et2 = t2.*1.152850836631063e+2;
et3 = t3.*(-7.222828668846019e-2);
et4 = 1.88489373009371e+1;
et5 = r1.*2.87999678991386+r2.*9.099866262276915;
et6 = t2.*(-7.222828668846019e-2);
et7 = t3.*9.110194750123977e+1;
et8 = -6.767203469478554;
Lx = [et1+et2+et3+et4,et5+et6+et7+et8];
end
