function Phix = DPhiDx(in1,in2,in3)
%DPhiDx
%    Phix = DPhiDx(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:24

r1 = in3(:,1);
r2 = in3(:,2);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = conj(x1);
t3 = conj(x2);
et1 = r1.*1.023436137921772e+3-r2.*3.246987961585796e+2;
et2 = t2.*1.152850836631063e+4;
et3 = t3.*(-7.222828668846019);
et4 = 1.88489373009371e+3;
et5 = r1.*2.87999678991386e+2+r2.*9.099866262276915e+2;
et6 = t2.*(-7.222828668846019);
et7 = t3.*9.110194750123977e+3;
et8 = -6.767203469478554e+2;
Phix = [et1+et2+et3+et4,et5+et6+et7+et8];
end
