function Cbar = valCbar(in1)
%valCbar
%    Cbar = valCbar(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:24

x1 = in1(:,1);
x2 = in1(:,2);
Cbar = [x1-1.0;x2-1.0;-x1-1.0;-x2-1.0];
end
