function L = valL(in1,in2,in3)
%valL
%    L = valL(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:23

r1 = in3(:,1);
r2 = in3(:,2);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = conj(x1);
t3 = conj(x2);
et1 = (r1+t2.*1.023436137921772e+1+t3.*2.87999678991386+1.459269473403313).^2;
et2 = 1.0./2.0;
et3 = (r2-t2.*3.246987961585796+t3.*9.099866262276915-1.20550066916638).^2;
et4 = 1.0./2.0;
L = et1.*et2+et3.*et4;
end
