function Phi = valPhi(in1,in2,in3)
%valPhi
%    Phi = valPhi(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-15 17:15:23

r1 = in3(:,1);
r2 = in3(:,2);
x1 = in1(:,1);
x2 = in1(:,2);
t2 = conj(x1);
t3 = conj(x2);
et1 = r1.*1.0e+2+t2.*1.023436137921772e+3+t3.*2.87999678991386e+2;
et2 = 1.459269473403313e+2;
et3 = et1+et2;
et4 = r1+t2.*1.023436137921772e+1+t3.*2.87999678991386+1.459269473403313;
et5 = 1.0./2.0;
et6 = r2.*1.0e+2-t2.*3.246987961585796e+2+t3.*9.099866262276915e+2;
et7 = -1.20550066916638e+2;
et8 = r2-t2.*3.246987961585796+t3.*9.099866262276915-1.20550066916638;
et9 = (et6+et7)./2.0;
Phi = et8.*et9+et3.*et4.*et5;
end
