function D_lowDim = D_lowDim(in1)
%D_lowDim
%    D_lowDim = D_lowDim(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-13 14:32:45

x1 = in1(:,1);
x2 = in1(:,2);
x3 = in1(:,3);
x4 = in1(:,4);
x5 = in1(:,5);
x6 = in1(:,6);
x7 = in1(:,7);
D_lowDim = [x1;x2;x3;x4;x5;x6;x7];
end
