function lift_full = lift_full(in1)
%LIFT_FULL
%    LIFT_FULL = LIFT_FULL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-13 14:32:44

zeta1 = in1(:,1);
zeta2 = in1(:,2);
zeta3 = in1(:,3);
zeta4 = in1(:,4);
zeta5 = in1(:,5);
zeta6 = in1(:,6);
zeta7 = in1(:,7);
zeta8 = in1(:,8);
zeta9 = in1(:,9);
zeta10 = in1(:,10);
zeta11 = in1(:,11);
zeta12 = in1(:,12);
zeta13 = in1(:,13);
zeta14 = in1(:,14);
zeta15 = in1(:,15);
zeta16 = in1(:,16);
et1 = -abs(zeta1+4.461540300782201e-1).^2-abs(zeta10+2.368830858139832e-1).^2-abs(zeta16-2.926260202225293e-1).^2-abs(zeta12-5.903998022741264e-1).^2;
et2 = -abs(zeta2+9.076572187376921e-1).^2-abs(zeta14+2.047120842353789e-2).^2-abs(zeta13+6.262547908912428e-1).^2-abs(zeta6+3.658010398782789e-1).^2;
et3 = -abs(zeta3+8.057364375283049e-1).^2-abs(zeta7-9.004440976767099e-1).^2-abs(zeta4-6.469156566545853e-1).^2-abs(zeta15+1.08827598578201e-1).^2;
et4 = -abs(zeta9+1.225112806872035e-1).^2-abs(zeta5-3.896572459516341e-1).^2-abs(zeta11-5.310335762980047e-1).^2-abs(zeta8+9.311078389941825e-1).^2;
et5 = -abs(zeta11-1.705355019595547e-1).^2-abs(zeta16-3.981534453133719e-1).^2-abs(zeta2-5.093733639647218e-1).^2-abs(zeta14+4.898097690814618e-1).^2;
et6 = -abs(zeta10+3.192285466677336e-1).^2-abs(zeta6+6.747765296107389e-1).^2-abs(zeta8+3.271896035714095e-3).^2-abs(zeta4-3.594053537073496e-1).^2;
et7 = -abs(zeta3+4.479498460028433e-1).^2-abs(zeta1-4.187296617161451e-1).^2-abs(zeta15-1.191410333028475e-2).^2-abs(zeta7+7.620046368832467e-1).^2;
et8 = -abs(zeta9-9.194879170321621e-1).^2-abs(zeta5-3.101960079476813e-1).^2-abs(zeta13-5.025341186113057e-1).^2-abs(zeta12+5.52376121017726e-1).^2;
lift_full = [zeta1;zeta2;zeta3;zeta4;zeta5;zeta6;zeta7;zeta8;zeta9;zeta10;zeta11;zeta12;zeta13;zeta14;zeta15;zeta16;exp(et1+et2+et3+et4);exp(et5+et6+et7+et8);1.0];
end
