function scaledown_u = scaledown_u(in1)
%SCALEDOWN_U
%    SCALEDOWN_U = SCALEDOWN_U(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-13 14:32:43

u1 = in1(:,1);
u2 = in1(:,2);
scaledown_u = [u1.*9.090914385626036e-4,u2.*9.091034734790225e-4];
end
