function scaleup_y = scaleup_y(in1)
%SCALEUP_Y
%    SCALEUP_Y = SCALEUP_Y(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-13 14:32:43

y1 = in1(:,1);
y2 = in1(:,2);
y3 = in1(:,3);
y4 = in1(:,4);
y5 = in1(:,5);
y6 = in1(:,6);
y7 = in1(:,7);
scaleup_y = [y1./2.0-7.0./5.0e+1,y2.*(5.11e+2./5.0e+1)-4.7e+1./2.5e+1,y3.*(4.31e+2./5.0e+1)+1.63e+2./1.0e+2,y4.*4.24e-2+5.2e-3,y5.*5.285e-2+1.105e-2,y6.*3.83e-2-7.8e-3,y7.*(3.9e+1./8.0e+2)-9.65e-3];
end
