function scaleup_u = scaleup_u(in1)
%SCALEUP_U
%    SCALEUP_U = SCALEUP_U(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-08-13 14:32:43

u1 = in1(:,1);
u2 = in1(:,2);
scaleup_u = [u1.*1.099999359339623e+3,u2.*1.099984797300497e+3];
end
